### ISSUE TITLE
Same access path for different arguments when a dotnet function is invoked from JavaScript multiple times

### ISSUE THREAD

**Issue by mingyaulee** [mingyaulee/JsBind.Net#3]
@mingyaulee 
The accesspath of multiple ports is the same

![image](https://dimg04.c-ctrip.com/images/0v56c120009598jql3AEC.png)

_Originally posted by @yuzd in https://github.com/mingyaulee/WebExtensions.Net/issues/14#issuecomment-980493848_

**Comment by mingyaulee** [comment]
@yuzd This has been fixed in release v0.2.9

**Comment by yuzd** [comment]
![image](https://dimg04.c-ctrip.com/images/0v5311200095bdtuuB523.png)
