### ISSUE TITLE
port.OnMessage.AddListener fail

### ISSUE THREAD

**Issue by yuzd** [mingyaulee/JsBind.Net#4]
@mingyaulee  version:0.3.0 port.OnMessage.AddListener fail
![image](https://dimg04.c-ctrip.com/images/0v5311200095bdtuuB523.png)

![image](https://user-images.githubusercontent.com/16083659/143734450-b4c10c5a-56c2-4f07-bc3d-76885c9155a9.png)

**Comment by mingyaulee** [comment]
This took me a while but I found the root cause of it. The fix has been released in v0.3.2

**Comment by yuzd** [comment]
great job！  this library is getting more fun and more useful
